In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

In [2]:
df = pd.read_csv("../data/processed/loan_risk_feature_engineered.csv")

df.head()

,Unnamed: 0,CustomerID,Age,Gender,MaritalStatus,Education,Occupation,EmploymentYears,AnnualIncome,MonthlyExpenses,...,FraudFlag,CustomerSegment,LoanApproved,MonthlyIncome,DisposableIncome,EMIRatio,SavingRatio,DebtToIncomeRatio,Networth,CreditUtilizationRatio
0,0,112424.0,36.0,Male,Single,PostGraduate,Salaried,25.0,6114208.0,190034.0,...,No,Regular,No,509517.333333,319483.333333,0.037881,0.751028,0.587899,7316519.0,0.192366
1,1,108271.0,25.0,Female,Single,HighSchool,SelfEmployed,30.0,4487423.0,24602.0,...,No,Regular,Yes,373951.916667,349349.916667,0.109621,1.979788,0.273935,13485542.0,0.085016
2,2,122724.0,32.0,Male,Single,Graduate,SelfEmployed,8.0,7493921.0,60028.0,...,No,Regular,Yes,624493.416667,564465.416667,0.078643,0.555598,0.495641,10186747.0,0.070233
3,3,112573.0,30.0,Female,Married,Graduate,Student,35.0,4152555.0,187520.0,...,No,Regular,Yes,346046.250000,158526.250000,0.163487,2.337600,0.611959,14080359.0,0.116370
4,4,112098.0,41.0,Female,Single,Graduate,Business,36.0,7929802.0,199257.0,...,No,Regular,No,660816.833333,461559.833333,0.075230,0.006726,0.238586,1209057.0,0.237283

In [3]:
df = df.drop(columns=["Unnamed: 0","CustomerID","FraudFlag","CustomerSegment"]
             )

In [4]:
df.shape

(25600, 38)

In [5]:
x = df.drop(columns=["LoanApproved"])
y = df["LoanApproved"]

In [6]:
label = LabelEncoder()
cat_col = x.select_dtypes(include="object").columns

for col in cat_col:
    x[col] = label.fit_transform(x[col])

y = label.fit_transform(y)

C:\Users\Pranavraj\AppData\Local\Temp\ipykernel_13260\4261542492.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_col = x.select_dtypes(include="object").columns

In [7]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,
                                                 random_state=42,
                                                 stratify=y)

In [8]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)

x_test = scaler.transform(x_test)

In [9]:
import joblib
joblib.dump(scaler,"../models/scaler.pkl")

['../models/scaler.pkl']

In [10]:
print(type(x_train))

print(x_train.shape)

print(x_test.shape)

<class 'numpy.ndarray'>
(20480, 37)
(5120, 37)

In [11]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report,
    roc_auc_score
)

from sklearn.linear_model import LogisticRegression

from sklearn.tree import DecisionTreeClassifier

from sklearn.ensemble import RandomForestClassifier

from sklearn.neighbors import KNeighborsClassifier

from sklearn.naive_bayes import GaussianNB

from sklearn.svm import SVC

from sklearn.ensemble import GradientBoostingClassifier

from sklearn.ensemble import AdaBoostClassifier

from sklearn.ensemble import ExtraTreesClassifier

In [12]:
def evaluate_model(model):
    model.fit(x_train,y_train)

    y_pred = model.predict(x_test)

    accuracy = accuracy_score(y_test,y_pred)

    precision = precision_score(y_test,y_pred)

    recall = recall_score(y_test,y_pred)

    f1 = f1_score(y_test,y_pred)

    roc = roc_auc_score(y_test,y_pred)


    print("="*60)
    print(model.__class__.__name__)
    print("="*60)

    print("Precision :", precision)
    print("Recall :", recall)
    print("F1 Score :", f1)
    print("ROC AUC :", roc)

    print("\nConfusion Matrix")

    print(confusion_matrix(y_test,y_pred))

    print("\nClassification Report")

    print(classification_report(y_test, y_pred))

In [13]:
lr = LogisticRegression()

evaluate_model(lr)

============================================================
LogisticRegression
============================================================
Precision : 0.9095373481519773
Recall : 0.9324324324324325
F1 Score : 0.9208426010728772
ROC AUC : 0.8362013573752058

Confusion Matrix
[[ 996  350]
 [ 255 3519]]

Classification Report
              precision    recall  f1-score   support

           0       0.80      0.74      0.77      1346
           1       0.91      0.93      0.92      3774

    accuracy                           0.88      5120
   macro avg       0.85      0.84      0.84      5120
weighted avg       0.88      0.88      0.88      5120

In [14]:
dt = DecisionTreeClassifier(
    random_state=42
)
evaluate_model(dt)

============================================================
DecisionTreeClassifier
============================================================
Precision : 0.9865541787503296
Recall : 0.9915209326974033
F1 Score : 0.9890313202061584
ROC AUC : 0.9768154440604402

Confusion Matrix
[[1295   51]
 [  32 3742]]

Classification Report
              precision    recall  f1-score   support

           0       0.98      0.96      0.97      1346
           1       0.99      0.99      0.99      3774

    accuracy                           0.98      5120
   macro avg       0.98      0.98      0.98      5120
weighted avg       0.98      0.98      0.98      5120

In [15]:
rf = RandomForestClassifier(random_state=42)
evaluate_model(rf)

============================================================
RandomForestClassifier
============================================================
Precision : 0.9894123875066173
Recall : 0.9904610492845787
F1 Score : 0.9899364406779662
ROC AUC : 0.9803716836318881

Confusion Matrix
[[1306   40]
 [  36 3738]]

Classification Report
              precision    recall  f1-score   support

           0       0.97      0.97      0.97      1346
           1       0.99      0.99      0.99      3774

    accuracy                           0.99      5120
   macro avg       0.98      0.98      0.98      5120
weighted avg       0.99      0.99      0.99      5120

In [16]:
knn = KNeighborsClassifier()
evaluate_model(knn)

============================================================
KNeighborsClassifier
============================================================
Precision : 0.8363073994765644
Recall : 0.9313725490196079
F1 Score : 0.8812836906105052
ROC AUC : 0.7101142091309035

Confusion Matrix
[[ 658  688]
 [ 259 3515]]

Classification Report
              precision    recall  f1-score   support

           0       0.72      0.49      0.58      1346
           1       0.84      0.93      0.88      3774

    accuracy                           0.82      5120
   macro avg       0.78      0.71      0.73      5120
weighted avg       0.81      0.82      0.80      5120

In [17]:
nb = GaussianNB()

evaluate_model(nb)

============================================================
GaussianNB
============================================================
Precision : 0.7653475935828877
Recall : 0.9480657127715951
F1 Score : 0.8469641377677831
ROC AUC : 0.5665291416755449

Confusion Matrix
[[ 249 1097]
 [ 196 3578]]

Classification Report
              precision    recall  f1-score   support

           0       0.56      0.18      0.28      1346
           1       0.77      0.95      0.85      3774

    accuracy                           0.75      5120
   macro avg       0.66      0.57      0.56      5120
weighted avg       0.71      0.75      0.70      5120

In [18]:
svm = SVC()
evaluate_model(svm)

============================================================
SVC
============================================================
Precision : 0.9108706852138073
Recall : 0.9369369369369369
F1 Score : 0.9237199582027168
ROC AUC : 0.8399394937284982

Confusion Matrix
[[1000  346]
 [ 238 3536]]

Classification Report
              precision    recall  f1-score   support

           0       0.81      0.74      0.77      1346
           1       0.91      0.94      0.92      3774

    accuracy                           0.89      5120
   macro avg       0.86      0.84      0.85      5120
weighted avg       0.88      0.89      0.88      5120

In [19]:
gb = GradientBoostingClassifier(random_state=42)
evaluate_model(gb)

============================================================
GradientBoostingClassifier
============================================================
Precision : 0.9899284389080307
Recall : 0.9896661367249603
F1 Score : 0.9897972704385849
ROC AUC : 0.9807171694025991

Confusion Matrix
[[1308   38]
 [  39 3735]]

Classification Report
              precision    recall  f1-score   support

           0       0.97      0.97      0.97      1346
           1       0.99      0.99      0.99      3774

    accuracy                           0.98      5120
   macro avg       0.98      0.98      0.98      5120
weighted avg       0.98      0.98      0.98      5120

In [21]:
ab = AdaBoostClassifier(random_state=42)
evaluate_model(ab)

============================================================
AdaBoostClassifier
============================================================
Precision : 0.9975851891601825
Recall : 0.9851616322204557
F1 Score : 0.9913344887348353
ROC AUC : 0.9892375768828876

Confusion Matrix
[[1337    9]
 [  56 3718]]

Classification Report
              precision    recall  f1-score   support

           0       0.96      0.99      0.98      1346
           1       1.00      0.99      0.99      3774

    accuracy                           0.99      5120
   macro avg       0.98      0.99      0.98      5120
weighted avg       0.99      0.99      0.99      5120

In [22]:
et = ExtraTreesClassifier(random_state=42)

evaluate_model(et)

============================================================
ExtraTreesClassifier
============================================================
Precision : 0.9455919395465995
Recall : 0.994700582935877
F1 Score : 0.9695247933884298
ROC AUC : 0.9171125500117722

Confusion Matrix
[[1130  216]
 [  20 3754]]

Classification Report
              precision    recall  f1-score   support

           0       0.98      0.84      0.91      1346
           1       0.95      0.99      0.97      3774

    accuracy                           0.95      5120
   macro avg       0.96      0.92      0.94      5120
weighted avg       0.96      0.95      0.95      5120

In [23]:
results = []
models ={
    "Logistic Regression": LogisticRegression(),

    "Decision Tree": DecisionTreeClassifier(random_state=42),

    "Random Forest": RandomForestClassifier(random_state=42),

    "KNN": KNeighborsClassifier(),

    "Naive Bayes": GaussianNB(),

    "SVM": SVC(),

    "Gradient Boosting": GradientBoostingClassifier(random_state=42),

    "AdaBoost": AdaBoostClassifier(random_state=42),

    "Extra Trees": ExtraTreesClassifier(random_state=42)
}

for name, model in models.items():
    model.fit(x_train,y_train)
    pred =  model.predict(x_test)
    results.append({
        "Model":name,
        "Accuracy":accuracy_score(y_test,pred),
        "Precision":precision_score(y_test,pred),
        "Recall":recall_score(y_test,pred),
        "F1 Score" :f1_score(y_test,pred)
    })



comparison = pd.DataFrame(results)

comparison.sort_values(
    by="Accuracy",
    ascending=False
)

                 Model  Accuracy  Precision    Recall  F1 Score
7             AdaBoost  0.987305   0.997585  0.985162  0.991334
2        Random Forest  0.985156   0.989412  0.990461  0.989936
6    Gradient Boosting  0.984961   0.989928  0.989666  0.989797
1        Decision Tree  0.983789   0.986554  0.991521  0.989031
8          Extra Trees  0.953906   0.945592  0.994701  0.969525
5                  SVM  0.885938   0.910871  0.936937  0.923720
0  Logistic Regression  0.881836   0.909537  0.932432  0.920843
3                  KNN  0.815039   0.836307  0.931373  0.881284
4          Naive Bayes  0.747461   0.765348  0.948066  0.846964